name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: archlinux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OCaml environment
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.14.1

      - name: Initialize opam
        run: |
          opam init -y --disable-sandboxing
          eval $(opam env)

      - name: Install dependencies
        run: |
          opam install dune menhir llvm.14.0.6 ppx_deriving odoc

      - name: Build project
        run: |
          dune build

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (opam, MSYS2)
        run: |
          winget install Git.Git OCaml.opam
          opam init -y --disable-sandboxing
          eval $(opam env)
          opam switch create 4.14.1
          opam install dune menhir llvm.14.0.6 ppx_deriving odoc

      - name: Build project
        run: |
          dune build
